"""ksp shipment models

Revision ID: 0a09c7a9605b
Revises: 683a1677fd58
Create Date: 2026-09-02 14:28:34.335328
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0a09c7a9605b"
down_revision: str | None = "683a1677fd58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.schema.CreateSchema(
            "warehouse_data",
            if_not_exists=True,
        )
    )
    op.create_table(
        "ksp_ship_headers",
        sa.Column("cust_ref", sa.String(), nullable=False),
        sa.Column("cust_po_no", sa.String(), nullable=False),
        sa.Column("delivered_to_wms_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("cust_ref", "cust_po_no"),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_po_no"),
        "ksp_ship_headers",
        ["cust_po_no"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_ref"),
        "ksp_ship_headers",
        ["cust_ref"],
        unique=True,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_delivered_to_wms_date"),
        "ksp_ship_headers",
        ["delivered_to_wms_date"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_order_status"),
        "ksp_ship_headers",
        ["order_status"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "ksp_ship_details",
        sa.Column("cust_ref", sa.String(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("tracking_no", sa.String(), nullable=False),
        sa.Column("tracking_no_secondary", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("package_weight_lbs", sa.Float(), nullable=False),
        sa.Column("dim_weight_lbs", sa.Float(), nullable=False),
        sa.Column("zone", sa.String(length=128), nullable=True),
        sa.Column("delivery_surcharge_type", sa.String(length=128), nullable=True),
        sa.Column("custom_1", sa.String(length=128), nullable=True),
        sa.Column("custom_2", sa.String(length=128), nullable=True),
        sa.Column("custom_3", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["cust_ref"],
            ["warehouse_data.ksp_ship_headers.cust_ref"],
        ),
        sa.PrimaryKeyConstraint("cust_ref", "tracking_no"),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_carrier"),
        "ksp_ship_details",
        ["carrier"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_cust_ref"),
        "ksp_ship_details",
        ["cust_ref"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_date"),
        "ksp_ship_details",
        ["date"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_tracking_no"),
        "ksp_ship_details",
        ["tracking_no"],
        unique=True,
        schema="warehouse_data",
    )
    op.create_table(
        "ksp_ship_detail_items",
        sa.Column("tracking_no", sa.String(), nullable=False),
        sa.Column("item", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("carton_code", sa.String(length=128), nullable=True),
        sa.Column("carton_num", sa.String(length=128), nullable=True),
        sa.Column("box_length_in", sa.String(length=128), nullable=True),
        sa.Column("box_width_in", sa.String(length=128), nullable=True),
        sa.Column("box_height_in", sa.String(length=128), nullable=True),
        sa.Column("package_weight_lbs", sa.String(length=128), nullable=True),
        sa.Column("lot_code", sa.String(length=128), nullable=True),
        sa.Column("serial_no", sa.String(length=128), nullable=True),
        sa.Column("custom_1", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["tracking_no"],
            ["warehouse_data.ksp_ship_details.tracking_no"],
        ),
        sa.PrimaryKeyConstraint("tracking_no", "item"),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_item"),
        "ksp_ship_detail_items",
        ["item"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_tracking_no"),
        "ksp_ship_detail_items",
        ["tracking_no"],
        unique=False,
        schema="warehouse_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_tracking_no"),
        table_name="ksp_ship_detail_items",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_item"),
        table_name="ksp_ship_detail_items",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_detail_items", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_tracking_no"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_date"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_cust_ref"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_carrier"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_details", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_order_status"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_delivered_to_wms_date"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_ref"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_po_no"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_headers", schema="warehouse_data")
    op.execute(
        sa.schema.DropSchema(
            "warehouse_data",
            if_exists=True,
        )
    )
    # ### end Alembic commands ###
