"""Sutton Tables

Revision ID: 102a6823e36c
Revises: 44c2252875be
Create Date: 2026-09-03 20:05:55.298471
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "102a6823e36c"
down_revision: str | None = "44c2252875be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS sutton")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edi_load",
        sa.Column("cust_acct", sa.String(), nullable=False),
        sa.Column("cust_order", sa.String(), nullable=False),
        sa.Column("style", sa.String(), nullable=False),
        sa.Column("order_num", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("customer", sa.String(), nullable=True),
        sa.Column("store_dc", sa.String(), nullable=True),
        sa.Column("dc", sa.String(), nullable=True),
        sa.Column("dept", sa.String(), nullable=True),
        sa.Column("date_edi", sa.Date(), nullable=True),
        sa.Column("ship_date", sa.Date(), nullable=True),
        sa.Column("cxl_date", sa.Date(), nullable=True),
        sa.Column("qty_ord", sa.Integer(), nullable=True),
        sa.Column("uom", sa.String(), nullable=True),
        sa.Column("ctns", sa.Integer(), nullable=True),
        sa.Column("cust_item", sa.String(), nullable=True),
        sa.Column("item_desc", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("ext_price", sa.Float(), nullable=True),
        sa.Column("ord_line", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "cust_acct", "cust_order", "style", "order_num", name="pk_edi_load"
        ),
        schema="sutton",
    )
    op.create_index(
        "idx_edi_cust_acct",
        "edi_load",
        ["cust_acct"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_edi_cust_order",
        "edi_load",
        ["cust_order"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_edi_customer",
        "edi_load",
        ["customer"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_edi_order_num",
        "edi_load",
        ["order_num"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_edi_ship_date",
        "edi_load",
        ["ship_date"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_edi_style", "edi_load", ["style"], unique=False, schema="sutton"
    )
    op.create_table(
        "inv_report",
        sa.Column("style", sa.String(), nullable=False),
        sa.Column("mstyle", sa.String(), nullable=True),
        sa.Column("control", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("unit_of_measure", sa.String(), nullable=True),
        sa.Column("season", sa.String(), nullable=True),
        sa.Column("selling_price", sa.Float(), nullable=True),
        sa.Column("first_cost", sa.Float(), nullable=True),
        sa.Column("landed_cost", sa.Float(), nullable=True),
        sa.Column("pack", sa.Integer(), nullable=True),
        sa.Column("carton_weight", sa.Float(), nullable=True),
        sa.Column("backordered_qty", sa.Integer(), nullable=True),
        sa.Column("allocated_qty", sa.Integer(), nullable=True),
        sa.Column("balance_prepaid", sa.Integer(), nullable=True),
        sa.Column("on_hand_qty", sa.Integer(), nullable=True),
        sa.Column("available_to_sell", sa.Integer(), nullable=True),
        sa.Column("prepaid", sa.Integer(), nullable=True),
        sa.Column("received", sa.Integer(), nullable=True),
        sa.Column("on_water", sa.Integer(), nullable=True),
        sa.Column("last_received_date", sa.Date(), nullable=True),
        sa.Column("last_shipped_date", sa.Date(), nullable=True),
        sa.Column("eta", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("style"),
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_inv_control",
        "inv_report",
        ["control"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_inv_mstyle",
        "inv_report",
        ["mstyle"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_inv_season",
        "inv_report",
        ["season"],
        unique=False,
        schema="sutton",
    )
    op.create_table(
        "open_order_report",
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("customer_acct", sa.String(), nullable=False),
        sa.Column("purchase_order", sa.String(), nullable=False),
        sa.Column("warehouse_batch", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("warehouse_order_number", sa.String(), nullable=True),
        sa.Column("warehouse_order_line", sa.String(), nullable=True),
        sa.Column("original_style", sa.String(), nullable=True),
        sa.Column("customer_sku", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_of_measure", sa.String(), nullable=True),
        sa.Column("unit_cost", sa.Float(), nullable=True),
        sa.Column("extended_cost", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "company",
            "customer_acct",
            "purchase_order",
            "warehouse_batch",
            "sku",
            name="pk_sutton_open_order",
        ),
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_oo_customer",
        "open_order_report",
        ["customer_acct"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_oo_po",
        "open_order_report",
        ["purchase_order"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_oo_sku",
        "open_order_report",
        ["sku"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_oo_status",
        "open_order_report",
        ["status"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_oo_warehouse_batch",
        "open_order_report",
        ["warehouse_batch"],
        unique=False,
        schema="sutton",
    )
    op.create_table(
        "order_submission",
        sa.Column("customer", sa.String(), nullable=False),
        sa.Column("purchase_order", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("cancel_date", sa.Date(), nullable=True),
        sa.Column("customer_sku", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("message_1", sa.String(), nullable=True),
        sa.Column("message_2", sa.String(), nullable=True),
        sa.Column("message_3", sa.String(), nullable=True),
        sa.Column("salesperson", sa.String(), nullable=True),
        sa.Column("smartsheet_row_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "customer", "purchase_order", "sku", name="pk_sutton_order_submission"
        ),
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_order_customer",
        "order_submission",
        ["customer"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_order_po",
        "order_submission",
        ["purchase_order"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_order_salesperson",
        "order_submission",
        ["salesperson"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_order_sku",
        "order_submission",
        ["sku"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_order_start_date",
        "order_submission",
        ["start_date"],
        unique=False,
        schema="sutton",
    )
    op.create_table(
        "sales_report",
        sa.Column("invoice", sa.Integer(), nullable=False),
        sa.Column("purchase_order", sa.String(), nullable=False),
        sa.Column("style", sa.String(), nullable=False),
        sa.Column("warehouse_batch_number", sa.String(), nullable=False),
        sa.Column("customer_number", sa.String(), nullable=True),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("salesman", sa.String(), nullable=True),
        sa.Column("salesman_code", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("item_description", sa.String(), nullable=True),
        sa.Column("customer_sku", sa.String(), nullable=True),
        sa.Column("selling_price", sa.Float(), nullable=True),
        sa.Column("sales_total", sa.Float(), nullable=True),
        sa.Column("qty_shipped", sa.Integer(), nullable=True),
        sa.Column("cartons_shipped", sa.Integer(), nullable=True),
        sa.Column("warehouse", sa.String(), nullable=True),
        sa.Column("carrier", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "invoice",
            "purchase_order",
            "style",
            "warehouse_batch_number",
            name="pk_sutton_sales",
        ),
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_customer",
        "sales_report",
        ["customer_number"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_date",
        "sales_report",
        ["date"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_invoice",
        "sales_report",
        ["invoice"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_po",
        "sales_report",
        ["purchase_order"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_salesman",
        "sales_report",
        ["salesman_code"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_style",
        "sales_report",
        ["style"],
        unique=False,
        schema="sutton",
    )
    op.create_index(
        "idx_sutton_sales_warehouse",
        "sales_report",
        ["warehouse"],
        unique=False,
        schema="sutton",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_sutton_sales_warehouse", table_name="sales_report", schema="sutton"
    )
    op.drop_index("idx_sutton_sales_style", table_name="sales_report", schema="sutton")
    op.drop_index(
        "idx_sutton_sales_salesman", table_name="sales_report", schema="sutton"
    )
    op.drop_index("idx_sutton_sales_po", table_name="sales_report", schema="sutton")
    op.drop_index(
        "idx_sutton_sales_invoice", table_name="sales_report", schema="sutton"
    )
    op.drop_index("idx_sutton_sales_date", table_name="sales_report", schema="sutton")
    op.drop_index(
        "idx_sutton_sales_customer", table_name="sales_report", schema="sutton"
    )
    op.drop_table("sales_report", schema="sutton")
    op.drop_index(
        "idx_sutton_order_start_date",
        table_name="order_submission",
        schema="sutton",
    )
    op.drop_index(
        "idx_sutton_order_sku", table_name="order_submission", schema="sutton"
    )
    op.drop_index(
        "idx_sutton_order_salesperson",
        table_name="order_submission",
        schema="sutton",
    )
    op.drop_index("idx_sutton_order_po", table_name="order_submission", schema="sutton")
    op.drop_index(
        "idx_sutton_order_customer",
        table_name="order_submission",
        schema="sutton",
    )
    op.drop_table("order_submission", schema="sutton")
    op.drop_index(
        "idx_sutton_oo_warehouse_batch",
        table_name="open_order_report",
        schema="sutton",
    )
    op.drop_index(
        "idx_sutton_oo_status", table_name="open_order_report", schema="sutton"
    )
    op.drop_index("idx_sutton_oo_sku", table_name="open_order_report", schema="sutton")
    op.drop_index("idx_sutton_oo_po", table_name="open_order_report", schema="sutton")
    op.drop_index(
        "idx_sutton_oo_customer", table_name="open_order_report", schema="sutton"
    )
    op.drop_table("open_order_report", schema="sutton")
    op.drop_index("idx_sutton_inv_season", table_name="inv_report", schema="sutton")
    op.drop_index("idx_sutton_inv_mstyle", table_name="inv_report", schema="sutton")
    op.drop_index("idx_sutton_inv_control", table_name="inv_report", schema="sutton")
    op.drop_table("inv_report", schema="sutton")
    op.drop_index("idx_edi_style", table_name="sedi_load", schema="sutton")
    op.drop_index("idx_edi_ship_date", table_name="edi_load", schema="sutton")
    op.drop_index("idx_edi_order_num", table_name="edi_load", schema="sutton")
    op.drop_index("idx_edi_customer", table_name="edi_load", schema="sutton")
    op.drop_index("idx_edi_cust_order", table_name="edi_load", schema="sutton")
    op.drop_index("idx_edi_cust_acct", table_name="edi_load", schema="sutton")
    op.drop_table("edi_load", schema="sutton")

    # ### end Alembic commands ###
