"""add shipment sync and productiv shipment tables

Revision ID: 44c2252875be
Revises: abf181ebf509
Create Date: 2026-09-03 13:30:05.925334
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "44c2252875be"
down_revision: str | None = "abf181ebf509"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productiv_ship_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("reference_num", sa.String(length=128), nullable=True),
        sa.Column("po_num", sa.String(length=128), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("fully_allocated", sa.Boolean(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=True),
        sa.Column("process_date", sa.DateTime(), nullable=True),
        sa.Column("pick_started", sa.Boolean(), nullable=True),
        sa.Column("pick_done_date", sa.DateTime(), nullable=True),
        sa.Column("pick_ticket_print_date", sa.DateTime(), nullable=True),
        sa.Column("pack_started", sa.Boolean(), nullable=True),
        sa.Column("pack_done_date", sa.DateTime(), nullable=True),
        sa.Column("small_parcel_ship_date", sa.DateTime(), nullable=True),
        sa.Column("parcel_label_type", sa.Integer(), nullable=True),
        sa.Column("ship_date", sa.DateTime(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.Column("facility_name", sa.String(length=255), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_name", sa.String(length=255), nullable=True),
        sa.Column("last_modified_date", sa.DateTime(), nullable=True),
        sa.Column("last_modified_by_id", sa.Integer(), nullable=True),
        sa.Column("last_modified_by_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("charges_pending", sa.Boolean(), nullable=True),
        sa.Column("earliest_ship_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("num_units_1", sa.Integer(), nullable=True),
        sa.Column("unit_1_name", sa.String(length=64), nullable=True),
        sa.Column("num_units_2", sa.Integer(), nullable=True),
        sa.Column("unit_2_name", sa.String(length=64), nullable=True),
        sa.Column("total_weight", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total_volume", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("billing_code", sa.String(length=64), nullable=True),
        sa.Column("routing_scac_code", sa.String(length=16), nullable=True),
        sa.Column("routing_carrier", sa.String(length=128), nullable=True),
        sa.Column("routing_mode", sa.String(length=32), nullable=True),
        sa.Column("routing_account", sa.String(length=64), nullable=True),
        sa.Column("routing_ship_point_zip", sa.String(length=32), nullable=True),
        sa.Column("routing_bill_of_lading", sa.String(length=128), nullable=True),
        sa.Column("routing_pickup_date", sa.DateTime(), nullable=True),
        sa.Column("routing_tracking_number", sa.String(length=128), nullable=True),
        sa.Column("ship_to_contact_id", sa.Integer(), nullable=True),
        sa.Column("ship_to_company_name", sa.String(length=255), nullable=True),
        sa.Column("ship_to_name", sa.String(length=255), nullable=True),
        sa.Column("ship_to_address_1", sa.String(length=255), nullable=True),
        sa.Column("ship_to_address_2", sa.String(length=255), nullable=True),
        sa.Column("ship_to_city", sa.String(length=128), nullable=True),
        sa.Column("ship_to_state", sa.String(length=64), nullable=True),
        sa.Column("ship_to_zip", sa.String(length=32), nullable=True),
        sa.Column("ship_to_country", sa.String(length=8), nullable=True),
        sa.Column("ship_to_phone", sa.String(length=64), nullable=True),
        sa.Column("ship_to_email", sa.String(length=255), nullable=True),
        sa.Column("ship_to_is_residential", sa.Boolean(), nullable=True),
        sa.Column("ship_to_address_status", sa.Integer(), nullable=True),
        sa.Column("bill_to_contact_id", sa.Integer(), nullable=True),
        sa.Column("bill_to_company_name", sa.String(length=255), nullable=True),
        sa.Column("bill_to_name", sa.String(length=255), nullable=True),
        sa.Column("bill_to_address_1", sa.String(length=255), nullable=True),
        sa.Column("bill_to_address_2", sa.String(length=255), nullable=True),
        sa.Column("bill_to_city", sa.String(length=128), nullable=True),
        sa.Column("bill_to_state", sa.String(length=64), nullable=True),
        sa.Column("bill_to_zip", sa.String(length=32), nullable=True),
        sa.Column("bill_to_country", sa.String(length=8), nullable=True),
        sa.Column("bill_to_phone", sa.String(length=64), nullable=True),
        sa.Column("bill_to_email", sa.String(length=255), nullable=True),
        sa.Column("bill_to_is_residential", sa.Boolean(), nullable=True),
        sa.Column("bill_to_address_status", sa.Integer(), nullable=True),
        sa.Column(
            "parcel_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="ux_productiv_ship_headers_order_id"),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_external_id"),
        "productiv_ship_headers",
        ["external_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_order_id"),
        "productiv_ship_headers",
        ["order_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_po_num"),
        "productiv_ship_headers",
        ["po_num"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_reference_num"),
        "productiv_ship_headers",
        ["reference_num"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_routing_bill_of_lading"),
        "productiv_ship_headers",
        ["routing_bill_of_lading"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_headers_routing_tracking_number"),
        "productiv_ship_headers",
        ["routing_tracking_number"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "productiv_ship_billing_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("header_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("charge_type", sa.Integer(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["header_id"],
            ["warehouse_data.productiv_ship_headers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "header_id",
            "sequence",
            name="ux_productiv_ship_billing_charges_header_sequence",
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_billing_charges_header_id"),
        "productiv_ship_billing_charges",
        ["header_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "productiv_ship_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("header_id", sa.Integer(), nullable=False),
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("fully_allocated", sa.Boolean(), nullable=True),
        sa.Column("unit_name", sa.String(length=64), nullable=True),
        sa.Column(
            "original_primary_qty", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("row_version", sa.String(length=128), nullable=True),
        sa.Column("productiv_item_id", sa.Integer(), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("weight_imperial", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("weight_metric", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "fulfill_inv_sale_price", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["header_id"],
            ["warehouse_data.productiv_ship_headers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_item_id", name="ux_productiv_ship_items_order_item_id"
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_items_header_id"),
        "productiv_ship_items",
        ["header_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_items_order_item_id"),
        "productiv_ship_items",
        ["order_item_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_items_productiv_item_id"),
        "productiv_ship_items",
        ["productiv_item_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_items_sku"),
        "productiv_ship_items",
        ["sku"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "productiv_ship_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("header_id", sa.Integer(), nullable=False),
        sa.Column("productiv_package_id", sa.Integer(), nullable=False),
        sa.Column("package_type_id", sa.Integer(), nullable=True),
        sa.Column("length", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("width", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("height", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("weight", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("tracking_number", sa.String(length=128), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("oversize", sa.Boolean(), nullable=True),
        sa.Column("ucc128", sa.Integer(), nullable=True),
        sa.Column("carton_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["header_id"],
            ["warehouse_data.productiv_ship_headers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "productiv_package_id", name="ux_productiv_ship_packages_package_id"
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_packages_carton_id"),
        "productiv_ship_packages",
        ["carton_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_packages_header_id"),
        "productiv_ship_packages",
        ["header_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_packages_productiv_package_id"),
        "productiv_ship_packages",
        ["productiv_package_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_packages_tracking_number"),
        "productiv_ship_packages",
        ["tracking_number"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "productiv_ship_billing_charge_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("billing_charge_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_transaction_price_calc_id", sa.Integer(), nullable=True),
        sa.Column("num_units", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("charge_label", sa.String(length=255), nullable=True),
        sa.Column("unit_description", sa.String(length=128), nullable=True),
        sa.Column("charge_per_unit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.Column("system_generated", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["billing_charge_id"],
            ["warehouse_data.productiv_ship_billing_charges.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "billing_charge_id",
            "warehouse_transaction_price_calc_id",
            name="ux_productiv_ship_billing_charge_details_calc_id",
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f(
            "ix_warehouse_data_productiv_ship_billing_charge_details_warehouse_transaction_price_calc_id"
        ),
        "productiv_ship_billing_charge_details",
        ["warehouse_transaction_price_calc_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f(
            "ix_warehouse_data_productiv_ship_billing_charge_details_billing_charge_id"
        ),
        "productiv_ship_billing_charge_details",
        ["billing_charge_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "productiv_ship_package_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("productiv_package_content_id", sa.Integer(), nullable=False),
        sa.Column("productiv_package_id", sa.Integer(), nullable=True),
        sa.Column("productiv_order_item_id", sa.Integer(), nullable=True),
        sa.Column("productiv_receive_item_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("productiv_item_id", sa.Integer(), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["warehouse_data.productiv_ship_packages.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "productiv_package_content_id",
            name="ux_productiv_ship_package_contents_content_id",
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_package_id"),
        "productiv_ship_package_contents",
        ["package_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_receive_item_id"
        ),
        "productiv_ship_package_contents",
        ["productiv_receive_item_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_package_content_id"
        ),
        "productiv_ship_package_contents",
        ["productiv_package_content_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_productiv_package_id"),
        "productiv_ship_package_contents",
        ["productiv_package_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_order_item_id"
        ),
        "productiv_ship_package_contents",
        ["productiv_order_item_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_productiv_item_id"),
        "productiv_ship_package_contents",
        ["productiv_item_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_sku"),
        "productiv_ship_package_contents",
        ["sku"],
        unique=False,
        schema="warehouse_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_sku"),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_productiv_item_id"),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_order_item_id"
        ),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_productiv_package_id"),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_package_content_id"
        ),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f(
            "ix_warehouse_data_productiv_ship_package_contents_productiv_receive_item_id"
        ),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_package_contents_package_id"),
        table_name="productiv_ship_package_contents",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_package_contents", schema="warehouse_data")
    op.drop_index(
        op.f(
            "ix_warehouse_data_productiv_ship_billing_charge_details_billing_charge_id"
        ),
        table_name="productiv_ship_billing_charge_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f(
            "ix_warehouse_data_productiv_ship_billing_charge_details_warehouse_transaction_price_calc_id"
        ),
        table_name="productiv_ship_billing_charge_details",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_billing_charge_details", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_packages_tracking_number"),
        table_name="productiv_ship_packages",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_packages_productiv_package_id"),
        table_name="productiv_ship_packages",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_packages_header_id"),
        table_name="productiv_ship_packages",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_packages_carton_id"),
        table_name="productiv_ship_packages",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_packages", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_items_sku"),
        table_name="productiv_ship_items",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_items_productiv_item_id"),
        table_name="productiv_ship_items",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_items_order_item_id"),
        table_name="productiv_ship_items",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_items_header_id"),
        table_name="productiv_ship_items",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_items", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_billing_charges_header_id"),
        table_name="productiv_ship_billing_charges",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_billing_charges", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_routing_tracking_number"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_routing_bill_of_lading"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_reference_num"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_po_num"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_order_id"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_productiv_ship_headers_external_id"),
        table_name="productiv_ship_headers",
        schema="warehouse_data",
    )
    op.drop_table("productiv_ship_headers", schema="warehouse_data")
    # ### end Alembic commands ###
