"""add sos purchase order tables

Revision ID: 5adc80155207
Revises: c4e8a1d2f903
Create Date: 2026-07-30 14:27:25.147642
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5adc80155207'
down_revision: str | None = 'c4e8a1d2f903'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starred', sa.Integer(), nullable=True),
    sa.Column('sync_token', sa.Integer(), server_default='0', nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_fullname', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('billing_company', sa.Text(), nullable=True),
    sa.Column('billing_contact', sa.Text(), nullable=True),
    sa.Column('billing_phone', sa.Text(), nullable=True),
    sa.Column('billing_email', sa.Text(), nullable=True),
    sa.Column('billing_address_name', sa.Text(), nullable=True),
    sa.Column('billing_address_type', sa.Text(), nullable=True),
    sa.Column('billing_address_line_1', sa.Text(), nullable=True),
    sa.Column('billing_address_line_2', sa.Text(), nullable=True),
    sa.Column('billing_address_line_3', sa.Text(), nullable=True),
    sa.Column('billing_address_line_4', sa.Text(), nullable=True),
    sa.Column('billing_address_line_5', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.Text(), nullable=True),
    sa.Column('billing_state_province', sa.Text(), nullable=True),
    sa.Column('billing_postal_code', sa.Text(), nullable=True),
    sa.Column('billing_country', sa.Text(), nullable=True),
    sa.Column('shipping_company', sa.Text(), nullable=True),
    sa.Column('shipping_contact', sa.Text(), nullable=True),
    sa.Column('shipping_phone', sa.Text(), nullable=True),
    sa.Column('shipping_email', sa.Text(), nullable=True),
    sa.Column('shipping_address_name', sa.Text(), nullable=True),
    sa.Column('shipping_address_type', sa.Text(), nullable=True),
    sa.Column('shipping_address_line_1', sa.Text(), nullable=True),
    sa.Column('shipping_address_line_2', sa.Text(), nullable=True),
    sa.Column('shipping_address_line_3', sa.Text(), nullable=True),
    sa.Column('shipping_address_line_4', sa.Text(), nullable=True),
    sa.Column('shipping_address_line_5', sa.Text(), nullable=True),
    sa.Column('shipping_city', sa.Text(), nullable=True),
    sa.Column('shipping_state_province', sa.Text(), nullable=True),
    sa.Column('shipping_postal_code', sa.Text(), nullable=True),
    sa.Column('shipping_country', sa.Text(), nullable=True),
    sa.Column('terms_id', sa.Integer(), nullable=True),
    sa.Column('terms_name', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('assigned_to_user_raw', sa.JSON(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('currency_name', sa.Text(), nullable=True),
    sa.Column('tax_code_id', sa.Integer(), nullable=True),
    sa.Column('tax_code_name', sa.Text(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_name', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.Text(), nullable=True),
    sa.Column('received_status', sa.String(length=64), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('vendor_message', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('vendor_notes', sa.Text(), nullable=True),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_ship', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('open_amount', sa.Float(), nullable=True),
    sa.Column('drop_ship', sa.Boolean(), nullable=True),
    sa.Column('blanket_po', sa.Boolean(), nullable=True),
    sa.Column('contract_manufacturing', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('pending_approval', sa.Boolean(), nullable=True),
    sa.Column('summary_only', sa.Boolean(), nullable=True),
    sa.Column('has_signature', sa.Boolean(), nullable=True),
    sa.Column('update_default_costs', sa.Boolean(), nullable=True),
    sa.Column('sync_message', sa.Text(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keys_raw', sa.JSON(), nullable=True),
    sa.Column('values_raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sos'
    )
    op.create_index(op.f('ix_sos_purchase_order_headers_date'), 'purchase_order_headers', ['date'], unique=False, schema='sos')
    op.create_table('purchase_order_custom_fields',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['sos.purchase_order_headers.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id', 'custom_field_id'),
    schema='sos'
    )
    op.create_table('purchase_order_header_linked_transactions',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['sos.purchase_order_headers.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id', 'linked_transaction_id', 'type', 'line_number'),
    schema='sos'
    )
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('vendor_part_number', sa.Text(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('job_raw', sa.JSON(), nullable=True),
    sa.Column('workcenter_raw', sa.JSON(), nullable=True),
    sa.Column('customer_raw', sa.JSON(), nullable=True),
    sa.Column('tax_taxable', sa.Boolean(), nullable=True),
    sa.Column('tax_tax_code_raw', sa.JSON(), nullable=True),
    sa.Column('tax_tax_exempt_reason_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=32), nullable=True),
    sa.Column('volume_unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('received', sa.Float(), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('uom_name', sa.String(length=64), nullable=True),
    sa.Column('bin', sa.Text(), nullable=True),
    sa.Column('lot', sa.Text(), nullable=True),
    sa.Column('lot_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('serials_raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['sos.purchase_order_headers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sos'
    )
    op.create_index(op.f('ix_sos_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False, schema='sos')
    op.create_table('purchase_order_line_linked_transactions',
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['sos.purchase_order_lines.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_line_id', 'linked_transaction_id', 'type', 'line_number'),
    schema='sos'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_order_line_linked_transactions', schema='sos')
    op.drop_index(op.f('ix_sos_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines', schema='sos')
    op.drop_table('purchase_order_lines', schema='sos')
    op.drop_table('purchase_order_header_linked_transactions', schema='sos')
    op.drop_table('purchase_order_custom_fields', schema='sos')
    op.drop_index(op.f('ix_sos_purchase_order_headers_date'), table_name='purchase_order_headers', schema='sos')
    op.drop_table('purchase_order_headers', schema='sos')
    # ### end Alembic commands ###
