"""add new application tables

Revision ID: 683a1677fd58
Revises: d4f6a8b2c913
Create Date: 2026-08-27 09:13:58.868297
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '683a1677fd58'
down_revision: str | None = 'd4f6a8b2c913'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS bh_api")
    op.execute("CREATE SCHEMA IF NOT EXISTS order_data")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbb_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=64), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('line_type', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('os_sku', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('os_order_number', sa.String(length=64), nullable=True),
    sa.Column('sofs_order_number', sa.String(length=64), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=128), nullable=True),
    sa.Column('supplier_sku', sa.String(length=64), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'source_row', name='ux_bbb_payout_file_row')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bh_api'
    )
    op.create_table('data_lake_cursors',
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source_name', 'entity_name')
    )
    op.create_index(op.f('ix_data_lake_cursors_entity_name'), 'data_lake_cursors', ['entity_name'], unique=False)
    op.create_index(op.f('ix_data_lake_cursors_source_name'), 'data_lake_cursors', ['source_name'], unique=False)
    op.create_table('guest_supply_po_headers',
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tax_exempt_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_address', sa.Text(), nullable=True),
    sa.Column('ship_name', sa.String(length=255), nullable=True),
    sa.Column('ship_address_1', sa.String(length=255), nullable=True),
    sa.Column('ship_address_2', sa.String(length=255), nullable=True),
    sa.Column('ship_city', sa.String(length=100), nullable=True),
    sa.Column('ship_state', sa.String(length=2), nullable=True),
    sa.Column('ship_zip', sa.String(length=10), nullable=True),
    sa.Column('ship_country', sa.String(length=64), nullable=True),
    sa.Column('ship_phone', sa.String(length=20), nullable=True),
    sa.Column('bill_name', sa.String(length=255), nullable=True),
    sa.Column('bill_address_1', sa.String(length=255), nullable=True),
    sa.Column('bill_address_2', sa.String(length=255), nullable=True),
    sa.Column('bill_city', sa.String(length=100), nullable=True),
    sa.Column('bill_state', sa.String(length=2), nullable=True),
    sa.Column('bill_zip', sa.String(length=10), nullable=True),
    sa.Column('bill_country', sa.String(length=64), nullable=True),
    sa.Column('bill_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('terms_payment', sa.String(length=50), nullable=True),
    sa.Column('terms_freight', sa.String(length=50), nullable=True),
    sa.Column('terms_carrier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('po_number'),
    schema='order_data'
    )
    op.create_index(op.f('ix_order_data_guest_supply_po_headers_po_date'), 'guest_supply_po_headers', ['po_date'], unique=False, schema='order_data')
    op.create_table('rithum_po_details',
    sa.Column('hub_line_id', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('hub_order_id', sa.BigInteger(), nullable=True),
    sa.Column('merchant_order_id', sa.String(), nullable=True),
    sa.Column('order_line_item_number', sa.BigInteger(), nullable=True),
    sa.Column('merchant_line_item_number', sa.BigInteger(), nullable=True),
    sa.Column('merchant_sku', sa.String(), nullable=True),
    sa.Column('vendor_sku', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('packing_slip_line_message', sa.String(), nullable=True),
    sa.Column('vendor_line_note', sa.String(), nullable=True),
    sa.Column('personalization_data', sa.String(), nullable=True),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('hub_line_id'),
    schema='order_data'
    )
    op.create_table('rithum_po_headers',
    sa.Column('hub_order_id', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('merchant_order_id', sa.String(), nullable=True),
    sa.Column('po_type_code', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('merchant_vendor_id', sa.String(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('order_item_count', sa.BigInteger(), nullable=True),
    sa.Column('packing_slip_message', sa.String(), nullable=True),
    sa.Column('vendor_notes', sa.String(), nullable=True),
    sa.Column('customer_order_id', sa.String(), nullable=True),
    sa.Column('customer_order_date', sa.Date(), nullable=True),
    sa.Column('shipping_method', sa.String(), nullable=True),
    sa.Column('ship_to_company_name', sa.String(), nullable=True),
    sa.Column('ship_to_name', sa.String(), nullable=True),
    sa.Column('ship_to_address_1', sa.String(), nullable=True),
    sa.Column('ship_to_address_2', sa.String(), nullable=True),
    sa.Column('ship_to_city', sa.String(), nullable=True),
    sa.Column('ship_to_state', sa.String(), nullable=True),
    sa.Column('ship_to_postal_code', sa.String(), nullable=True),
    sa.Column('ship_to_country', sa.String(), nullable=True),
    sa.Column('ship_to_day_phone', sa.String(), nullable=True),
    sa.Column('ship_to_email', sa.String(), nullable=True),
    sa.Column('bill_to_company_name', sa.String(), nullable=True),
    sa.Column('bill_to_name', sa.String(), nullable=True),
    sa.Column('bill_to_address_1', sa.String(), nullable=True),
    sa.Column('bill_to_city', sa.String(), nullable=True),
    sa.Column('bill_to_state', sa.String(), nullable=True),
    sa.Column('bill_to_postal_code', sa.String(), nullable=True),
    sa.Column('bill_to_country', sa.String(), nullable=True),
    sa.Column('buying_contract', sa.String(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('order_currency', sa.String(), nullable=True),
    sa.Column('freight_payment_terms', sa.String(), nullable=True),
    sa.Column('erp_customer_order_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hub_order_id'),
    schema='order_data'
    )
    op.create_table('processed_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('report_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id', name='ux_payout_id')
    )
    op.create_table('target_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('report_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id', name='ux_target_payout_id')
    )
    op.create_table('wayfair_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remittance_number', sa.String(length=64), nullable=False),
    sa.Column('remittance_date', sa.Date(), nullable=True),
    sa.Column('deduction_invoice_number', sa.String(length=128), nullable=False),
    sa.Column('deduction_date', sa.Date(), nullable=True),
    sa.Column('deduction_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('item_sku', sa.String(length=128), nullable=True),
    sa.Column('credit_id', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remittance_number', 'source_file', 'source_row', name='ux_wayfair_deductions_file_row')
    )
    op.create_table('wayfair_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remittance_number', sa.String(length=64), nullable=False),
    sa.Column('remittance_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=False),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('product_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('birch_lane_allowance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('joss_main_allowance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('all_modern_allowance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('wayfair_allowance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('shipping_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_vat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('business', sa.String(length=64), nullable=True),
    sa.Column('order_type', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remittance_number', 'source_file', 'source_row', name='ux_wayfair_payments_file_row')
    )
    op.create_table('guest_supply_po_details',
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['po_number'], ['order_data.guest_supply_po_headers.po_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('po_number', 'line_num', 'sku', name='pk_guest_supply_po_detail'),
    schema='order_data'
    )
    op.create_index('idx_guest_supply_po_detail_po_number', 'guest_supply_po_details', ['po_number'], unique=False, schema='order_data')
    op.create_index('idx_guest_supply_po_detail_sku', 'guest_supply_po_details', ['sku'], unique=False, schema='order_data')
    op.create_table('target_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.String(length=64), nullable=False),
    sa.Column('transfer_type', sa.String(length=32), nullable=True),
    sa.Column('payout_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('tcin', sa.String(length=64), nullable=True),
    sa.Column('seller_sku', sa.String(length=128), nullable=True),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('original_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('line_total_less_discounts', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('referral_fee', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('shipping_and_services', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('referral_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['target_payouts.payout_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', name='ux_target_transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_transfers')
    op.drop_index('idx_guest_supply_po_detail_sku', table_name='guest_supply_po_details', schema='order_data')
    op.drop_index('idx_guest_supply_po_detail_po_number', table_name='guest_supply_po_details', schema='order_data')
    op.drop_table('guest_supply_po_details', schema='order_data')
    op.drop_table('wayfair_payments')
    op.drop_table('wayfair_deductions')
    op.drop_table('target_payouts')
    op.drop_table('processed_payouts')
    op.drop_table('rithum_po_headers', schema='order_data')
    op.drop_table('rithum_po_details', schema='order_data')
    op.drop_index(op.f('ix_order_data_guest_supply_po_headers_po_date'), table_name='guest_supply_po_headers', schema='order_data')
    op.drop_table('guest_supply_po_headers', schema='order_data')
    op.drop_index(op.f('ix_data_lake_cursors_source_name'), table_name='data_lake_cursors')
    op.drop_index(op.f('ix_data_lake_cursors_entity_name'), table_name='data_lake_cursors')
    op.drop_table('data_lake_cursors')
    op.drop_table('webhook_events', schema='bh_api')
    op.drop_table('bbb_payouts')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS order_data")
    op.execute("DROP SCHEMA IF EXISTS bh_api")
