"""add SOS document, customer, payment, and adjustment tables

Revision ID: 814b23355530
Revises: 5adc80155207
Create Date: 2026-07-30 14:36:41.721201
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "814b23355530"
down_revision: str | None = "5adc80155207"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "return_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("populate_from_object_type", sa.String(length=64), nullable=True),
        sa.Column("populate_from_id", sa.Integer(), nullable=True),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("customer_fullname", sa.Text(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("currency_name", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("sales_rep_raw", sa.JSON(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("shipping_method_id", sa.Integer(), nullable=True),
        sa.Column("shipping_method_name", sa.Text(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("customer_message", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("ship_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipping_amount", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("create_credit_memo", sa.Boolean(), nullable=True),
        sa.Column("create_bill_for_shipping_amount", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_return_headers_date"),
        "return_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "return_custom_fields",
        sa.Column("return_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["sos.return_headers.id"],
        ),
        sa.PrimaryKeyConstraint("return_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "return_header_linked_transactions",
        sa.Column("return_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["sos.return_headers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "return_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "return_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("return_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("tax_taxable", sa.Boolean(), nullable=True),
        sa.Column("tax_tax_code_raw", sa.JSON(), nullable=True),
        sa.Column("tax_tax_exempt_reason_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("weight_unit", sa.String(length=32), nullable=True),
        sa.Column("volume_unit", sa.String(length=32), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("alt_amount", sa.Float(), nullable=True),
        sa.Column("picked", sa.Float(), nullable=True),
        sa.Column("shipped", sa.Float(), nullable=True),
        sa.Column("invoiced", sa.Float(), nullable=True),
        sa.Column("produced", sa.Float(), nullable=True),
        sa.Column("returned", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("list_price", sa.Float(), nullable=True),
        sa.Column("percent_discount", sa.Float(), nullable=True),
        sa.Column("back_ordered", sa.Float(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("uom_name", sa.String(length=64), nullable=True),
        sa.Column("bin", sa.Text(), nullable=True),
        sa.Column("lot", sa.Text(), nullable=True),
        sa.Column("serials_raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["sos.return_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_return_lines_return_id"),
        "return_lines",
        ["return_id"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "return_line_linked_transactions",
        sa.Column("return_line_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["return_line_id"],
            ["sos.return_lines.id"],
        ),
        sa.PrimaryKeyConstraint(
            "return_line_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "rma_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("customer_fullname", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("billing_company", sa.Text(), nullable=True),
        sa.Column("billing_contact", sa.Text(), nullable=True),
        sa.Column("billing_phone", sa.Text(), nullable=True),
        sa.Column("billing_email", sa.Text(), nullable=True),
        sa.Column("billing_address_name", sa.Text(), nullable=True),
        sa.Column("billing_address_type", sa.Text(), nullable=True),
        sa.Column("billing_address_line_1", sa.Text(), nullable=True),
        sa.Column("billing_address_line_2", sa.Text(), nullable=True),
        sa.Column("billing_address_line_3", sa.Text(), nullable=True),
        sa.Column("billing_address_line_4", sa.Text(), nullable=True),
        sa.Column("billing_address_line_5", sa.Text(), nullable=True),
        sa.Column("billing_city", sa.Text(), nullable=True),
        sa.Column("billing_state_province", sa.Text(), nullable=True),
        sa.Column("billing_postal_code", sa.Text(), nullable=True),
        sa.Column("billing_country", sa.Text(), nullable=True),
        sa.Column("shipping_company", sa.Text(), nullable=True),
        sa.Column("shipping_contact", sa.Text(), nullable=True),
        sa.Column("shipping_phone", sa.Text(), nullable=True),
        sa.Column("shipping_email", sa.Text(), nullable=True),
        sa.Column("shipping_address_name", sa.Text(), nullable=True),
        sa.Column("shipping_address_type", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_1", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_2", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_3", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_4", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_5", sa.Text(), nullable=True),
        sa.Column("shipping_city", sa.Text(), nullable=True),
        sa.Column("shipping_state_province", sa.Text(), nullable=True),
        sa.Column("shipping_postal_code", sa.Text(), nullable=True),
        sa.Column("shipping_country", sa.Text(), nullable=True),
        sa.Column("sales_rep_raw", sa.JSON(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("return_status", sa.String(length=64), nullable=True),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipping_method_id", sa.Integer(), nullable=True),
        sa.Column("shipping_method_name", sa.Text(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=True),
        sa.Column("customer_message", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_rma_headers_date"),
        "rma_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "rma_custom_fields",
        sa.Column("rma_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["rma_id"],
            ["sos.rma_headers.id"],
        ),
        sa.PrimaryKeyConstraint("rma_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "rma_header_linked_transactions",
        sa.Column("rma_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rma_id"],
            ["sos.rma_headers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "rma_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "rma_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rma_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("tax_taxable", sa.Boolean(), nullable=True),
        sa.Column("tax_tax_code_raw", sa.JSON(), nullable=True),
        sa.Column("tax_tax_exempt_reason_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("weight_unit", sa.String(length=32), nullable=True),
        sa.Column("volume_unit", sa.String(length=32), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("alt_amount", sa.Float(), nullable=True),
        sa.Column("picked", sa.Float(), nullable=True),
        sa.Column("shipped", sa.Float(), nullable=True),
        sa.Column("invoiced", sa.Float(), nullable=True),
        sa.Column("produced", sa.Float(), nullable=True),
        sa.Column("returned", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("list_price", sa.Float(), nullable=True),
        sa.Column("percent_discount", sa.Float(), nullable=True),
        sa.Column("back_ordered", sa.Float(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("uom_name", sa.String(length=64), nullable=True),
        sa.Column("bin", sa.Text(), nullable=True),
        sa.Column("lot", sa.Text(), nullable=True),
        sa.Column("serials_raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rma_id"],
            ["sos.rma_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_rma_lines_rma_id"),
        "rma_lines",
        ["rma_id"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "rma_line_linked_transactions",
        sa.Column("rma_line_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rma_line_id"],
            ["sos.rma_lines.id"],
        ),
        sa.PrimaryKeyConstraint(
            "rma_line_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "sales_receipt_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fs_payment_id", sa.Integer(), nullable=True),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("customer_fullname", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("billing_company", sa.Text(), nullable=True),
        sa.Column("billing_contact", sa.Text(), nullable=True),
        sa.Column("billing_phone", sa.Text(), nullable=True),
        sa.Column("billing_email", sa.Text(), nullable=True),
        sa.Column("billing_address_name", sa.Text(), nullable=True),
        sa.Column("billing_address_type", sa.Text(), nullable=True),
        sa.Column("billing_address_line_1", sa.Text(), nullable=True),
        sa.Column("billing_address_line_2", sa.Text(), nullable=True),
        sa.Column("billing_address_line_3", sa.Text(), nullable=True),
        sa.Column("billing_address_line_4", sa.Text(), nullable=True),
        sa.Column("billing_address_line_5", sa.Text(), nullable=True),
        sa.Column("billing_city", sa.Text(), nullable=True),
        sa.Column("billing_state_province", sa.Text(), nullable=True),
        sa.Column("billing_postal_code", sa.Text(), nullable=True),
        sa.Column("billing_country", sa.Text(), nullable=True),
        sa.Column("shipping_company", sa.Text(), nullable=True),
        sa.Column("shipping_contact", sa.Text(), nullable=True),
        sa.Column("shipping_phone", sa.Text(), nullable=True),
        sa.Column("shipping_email", sa.Text(), nullable=True),
        sa.Column("shipping_address_name", sa.Text(), nullable=True),
        sa.Column("shipping_address_type", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_1", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_2", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_3", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_4", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_5", sa.Text(), nullable=True),
        sa.Column("shipping_city", sa.Text(), nullable=True),
        sa.Column("shipping_state_province", sa.Text(), nullable=True),
        sa.Column("shipping_postal_code", sa.Text(), nullable=True),
        sa.Column("shipping_country", sa.Text(), nullable=True),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("payment_method_name", sa.Text(), nullable=True),
        sa.Column("payment_method_sync_token", sa.Integer(), nullable=True),
        sa.Column(
            "payment_method_sos_pay_type",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column("deposit_account_id", sa.Integer(), nullable=True),
        sa.Column("deposit_account_name", sa.Text(), nullable=True),
        sa.Column("sales_rep_raw", sa.JSON(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("priority_id", sa.Integer(), nullable=True),
        sa.Column("priority_name", sa.Text(), nullable=True),
        sa.Column("assigned_to_user_raw", sa.JSON(), nullable=True),
        sa.Column("order_stage_id", sa.Integer(), nullable=True),
        sa.Column("order_stage_name", sa.Text(), nullable=True),
        sa.Column("tax_code_id", sa.Integer(), nullable=True),
        sa.Column("tax_code_name", sa.Text(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("currency_name", sa.Text(), nullable=True),
        sa.Column("shipping_method_id", sa.Integer(), nullable=True),
        sa.Column("shipping_method_name", sa.Text(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=True),
        sa.Column("ship_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_location_quickbooks", sa.Text(), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("customer_message", sa.Text(), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("can_ship", sa.String(length=64), nullable=True),
        sa.Column("account_token", sa.Text(), nullable=True),
        sa.Column("customer_po", sa.Text(), nullable=True),
        sa.Column("deposit_amount", sa.Float(), nullable=True),
        sa.Column("sub_total", sa.Float(), nullable=True),
        sa.Column("discount_percent", sa.Float(), nullable=True),
        sa.Column("discount_amount", sa.Float(), nullable=True),
        sa.Column("tax_percent", sa.Float(), nullable=True),
        sa.Column("tax_amount", sa.Float(), nullable=True),
        sa.Column("shipping_amount", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("discount_taxable", sa.Boolean(), nullable=True),
        sa.Column("shipping_taxable", sa.Boolean(), nullable=True),
        sa.Column("drop_ship", sa.Boolean(), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("store_customer_token", sa.Boolean(), nullable=True),
        sa.Column("force_save", sa.Boolean(), nullable=True),
        sa.Column("earliest_due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_link", sa.Text(), nullable=True),
        sa.Column("sync_message", sa.Text(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sos_pay_raw", sa.JSON(), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_sales_receipt_headers_date"),
        "sales_receipt_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "sales_receipt_custom_fields",
        sa.Column("sales_receipt_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["sales_receipt_id"],
            ["sos.sales_receipt_headers.id"],
        ),
        sa.PrimaryKeyConstraint("sales_receipt_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "sales_receipt_header_linked_transactions",
        sa.Column("sales_receipt_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sales_receipt_id"],
            ["sos.sales_receipt_headers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "sales_receipt_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "sales_receipt_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sales_receipt_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("tax_taxable", sa.Boolean(), nullable=True),
        sa.Column("tax_tax_code_raw", sa.JSON(), nullable=True),
        sa.Column("tax_tax_exempt_reason_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("weight_unit", sa.String(length=32), nullable=True),
        sa.Column("volume_unit", sa.String(length=32), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("alt_amount", sa.Float(), nullable=True),
        sa.Column("picked", sa.Float(), nullable=True),
        sa.Column("shipped", sa.Float(), nullable=True),
        sa.Column("invoiced", sa.Float(), nullable=True),
        sa.Column("produced", sa.Float(), nullable=True),
        sa.Column("returned", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("list_price", sa.Float(), nullable=True),
        sa.Column("percent_discount", sa.Float(), nullable=True),
        sa.Column("back_ordered", sa.Float(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("uom_name", sa.String(length=64), nullable=True),
        sa.Column("bin", sa.Text(), nullable=True),
        sa.Column("lot", sa.Text(), nullable=True),
        sa.Column("serials_raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sales_receipt_id"],
            ["sos.sales_receipt_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_sales_receipt_lines_sales_receipt_id"),
        "sales_receipt_lines",
        ["sales_receipt_id"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "sales_receipt_line_linked_transactions",
        sa.Column("sales_receipt_line_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sales_receipt_line_id"],
            ["sos.sales_receipt_lines.id"],
        ),
        sa.PrimaryKeyConstraint(
            "sales_receipt_line_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "estimate_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("customer_fullname", sa.Text(), nullable=True),
        sa.Column("billing_company", sa.Text(), nullable=True),
        sa.Column("billing_contact", sa.Text(), nullable=True),
        sa.Column("billing_phone", sa.Text(), nullable=True),
        sa.Column("billing_email", sa.Text(), nullable=True),
        sa.Column("billing_address_name", sa.Text(), nullable=True),
        sa.Column("billing_address_type", sa.Text(), nullable=True),
        sa.Column("billing_address_line_1", sa.Text(), nullable=True),
        sa.Column("billing_address_line_2", sa.Text(), nullable=True),
        sa.Column("billing_address_line_3", sa.Text(), nullable=True),
        sa.Column("billing_address_line_4", sa.Text(), nullable=True),
        sa.Column("billing_address_line_5", sa.Text(), nullable=True),
        sa.Column("billing_city", sa.Text(), nullable=True),
        sa.Column("billing_state_province", sa.Text(), nullable=True),
        sa.Column("billing_postal_code", sa.Text(), nullable=True),
        sa.Column("billing_country", sa.Text(), nullable=True),
        sa.Column("shipping_company", sa.Text(), nullable=True),
        sa.Column("shipping_contact", sa.Text(), nullable=True),
        sa.Column("shipping_phone", sa.Text(), nullable=True),
        sa.Column("shipping_email", sa.Text(), nullable=True),
        sa.Column("shipping_address_name", sa.Text(), nullable=True),
        sa.Column("shipping_address_type", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_1", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_2", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_3", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_4", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_5", sa.Text(), nullable=True),
        sa.Column("shipping_city", sa.Text(), nullable=True),
        sa.Column("shipping_state_province", sa.Text(), nullable=True),
        sa.Column("shipping_postal_code", sa.Text(), nullable=True),
        sa.Column("shipping_country", sa.Text(), nullable=True),
        sa.Column("sales_rep_raw", sa.JSON(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("tax_code_id", sa.Integer(), nullable=True),
        sa.Column("tax_code_name", sa.Text(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("currency_name", sa.Text(), nullable=True),
        sa.Column("transaction_location_quickbooks", sa.Text(), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("customer_message", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("deposit_amount", sa.Float(), nullable=True),
        sa.Column("sub_total", sa.Float(), nullable=True),
        sa.Column("discount_percent", sa.Float(), nullable=True),
        sa.Column("discount_amount", sa.Float(), nullable=True),
        sa.Column("tax_percent", sa.Float(), nullable=True),
        sa.Column("tax_amount", sa.Float(), nullable=True),
        sa.Column("shipping_amount", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("discount_taxable", sa.Boolean(), nullable=True),
        sa.Column("shipping_taxable", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("accepted_by_raw", sa.JSON(), nullable=True),
        sa.Column("accepted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("force_save", sa.Boolean(), nullable=True),
        sa.Column("sync_message", sa.Text(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_estimate_headers_date"),
        "estimate_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "estimate_custom_fields",
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["sos.estimate_headers.id"],
        ),
        sa.PrimaryKeyConstraint("estimate_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "estimate_header_linked_transactions",
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["sos.estimate_headers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "estimate_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "estimate_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("tax_taxable", sa.Boolean(), nullable=True),
        sa.Column("tax_tax_code_raw", sa.JSON(), nullable=True),
        sa.Column("tax_tax_exempt_reason_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("weight_unit", sa.String(length=32), nullable=True),
        sa.Column("volume_unit", sa.String(length=32), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("alt_amount", sa.Float(), nullable=True),
        sa.Column("picked", sa.Float(), nullable=True),
        sa.Column("shipped", sa.Float(), nullable=True),
        sa.Column("invoiced", sa.Float(), nullable=True),
        sa.Column("produced", sa.Float(), nullable=True),
        sa.Column("returned", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("list_price", sa.Float(), nullable=True),
        sa.Column("percent_discount", sa.Float(), nullable=True),
        sa.Column("back_ordered", sa.Float(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("uom_name", sa.String(length=64), nullable=True),
        sa.Column("bin", sa.Text(), nullable=True),
        sa.Column("lot", sa.Text(), nullable=True),
        sa.Column("serials_raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["sos.estimate_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_estimate_lines_estimate_id"),
        "estimate_lines",
        ["estimate_id"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "estimate_line_linked_transactions",
        sa.Column("estimate_line_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_line_id"],
            ["sos.estimate_lines.id"],
        ),
        sa.PrimaryKeyConstraint(
            "estimate_line_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("fullname", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("parent_name", sa.Text(), nullable=True),
        sa.Column("parent_fullname", sa.Text(), nullable=True),
        sa.Column("sublevel", sa.Integer(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("mobile", sa.Text(), nullable=True),
        sa.Column("alt_phone", sa.Text(), nullable=True),
        sa.Column("fax", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("portal_password", sa.Text(), nullable=True),
        sa.Column("contact_title", sa.Text(), nullable=True),
        sa.Column("contact_first_name", sa.Text(), nullable=True),
        sa.Column("contact_middle_name", sa.Text(), nullable=True),
        sa.Column("contact_last_name", sa.Text(), nullable=True),
        sa.Column("contact_suffix", sa.Text(), nullable=True),
        sa.Column("billing_address_line_1", sa.Text(), nullable=True),
        sa.Column("billing_address_line_2", sa.Text(), nullable=True),
        sa.Column("billing_address_line_3", sa.Text(), nullable=True),
        sa.Column("billing_address_line_4", sa.Text(), nullable=True),
        sa.Column("billing_address_line_5", sa.Text(), nullable=True),
        sa.Column("billing_city", sa.Text(), nullable=True),
        sa.Column("billing_state_province", sa.Text(), nullable=True),
        sa.Column("billing_postal_code", sa.Text(), nullable=True),
        sa.Column("billing_country", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_1", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_2", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_3", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_4", sa.Text(), nullable=True),
        sa.Column("shipping_address_line_5", sa.Text(), nullable=True),
        sa.Column("shipping_city", sa.Text(), nullable=True),
        sa.Column("shipping_state_province", sa.Text(), nullable=True),
        sa.Column("shipping_postal_code", sa.Text(), nullable=True),
        sa.Column("shipping_country", sa.Text(), nullable=True),
        sa.Column("terms_id", sa.Integer(), nullable=True),
        sa.Column("terms_name", sa.Text(), nullable=True),
        sa.Column("price_tier_id", sa.Integer(), nullable=True),
        sa.Column("price_tier_name", sa.Text(), nullable=True),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("payment_method_name", sa.Text(), nullable=True),
        sa.Column("payment_method_sync_token", sa.Integer(), nullable=True),
        sa.Column(
            "payment_method_sos_pay_type",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column("sales_rep_raw", sa.JSON(), nullable=True),
        sa.Column("customer_type_id", sa.Integer(), nullable=True),
        sa.Column("customer_type_name", sa.Text(), nullable=True),
        sa.Column("resale_number", sa.Text(), nullable=True),
        sa.Column("contractor_number", sa.Text(), nullable=True),
        sa.Column("business_license", sa.Text(), nullable=True),
        sa.Column("found_us_via_raw", sa.JSON(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("currency_name", sa.Text(), nullable=True),
        sa.Column("tax_taxable", sa.Boolean(), nullable=True),
        sa.Column("tax_tax_code_raw", sa.JSON(), nullable=True),
        sa.Column("tax_tax_exempt_reason_id", sa.String(length=64), nullable=True),
        sa.Column("credit_hold", sa.Boolean(), nullable=True),
        sa.Column("bill_with_parent", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("has_children", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("is_in_quick_books", sa.Boolean(), nullable=True),
        sa.Column("sync_message", sa.Text(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("has_card_on_file", sa.Boolean(), nullable=True),
        sa.Column("last_four", sa.String(length=4), nullable=True),
        sa.Column("exp_month", sa.Integer(), nullable=True),
        sa.Column("exp_year", sa.Integer(), nullable=True),
        sa.Column("token_type", sa.String(length=64), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_table(
        "customer_custom_fields",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["sos.customers.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "customer_alt_addresses",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("address_index", sa.Integer(), nullable=False),
        sa.Column("company", sa.Text(), nullable=True),
        sa.Column("contact", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("address_name", sa.Text(), nullable=True),
        sa.Column("address_type", sa.Text(), nullable=True),
        sa.Column("address_line_1", sa.Text(), nullable=True),
        sa.Column("address_line_2", sa.Text(), nullable=True),
        sa.Column("address_line_3", sa.Text(), nullable=True),
        sa.Column("address_line_4", sa.Text(), nullable=True),
        sa.Column("address_line_5", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state_province", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["sos.customers.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id", "address_index"),
        schema="sos",
    )
    op.create_table(
        "payment_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sync_message", sa.Text(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=True),
        sa.Column("customer_fullname", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("payment_method_name", sa.Text(), nullable=True),
        sa.Column("payment_method_sync_token", sa.Integer(), nullable=True),
        sa.Column(
            "payment_method_sos_pay_type",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("currency_name", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("deposit_account_id", sa.Integer(), nullable=True),
        sa.Column("deposit_account_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("billing_company", sa.Text(), nullable=True),
        sa.Column("billing_contact", sa.Text(), nullable=True),
        sa.Column("billing_phone", sa.Text(), nullable=True),
        sa.Column("billing_email", sa.Text(), nullable=True),
        sa.Column("billing_address_name", sa.Text(), nullable=True),
        sa.Column("billing_address_type", sa.Text(), nullable=True),
        sa.Column("billing_address_line_1", sa.Text(), nullable=True),
        sa.Column("billing_address_line_2", sa.Text(), nullable=True),
        sa.Column("billing_address_line_3", sa.Text(), nullable=True),
        sa.Column("billing_address_line_4", sa.Text(), nullable=True),
        sa.Column("billing_address_line_5", sa.Text(), nullable=True),
        sa.Column("billing_city", sa.Text(), nullable=True),
        sa.Column("billing_state_province", sa.Text(), nullable=True),
        sa.Column("billing_postal_code", sa.Text(), nullable=True),
        sa.Column("billing_country", sa.Text(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("customer_message", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("documents_raw", sa.JSON(), nullable=True),
        sa.Column("check_number", sa.Text(), nullable=True),
        sa.Column("create_customer_if_not_found", sa.Boolean(), nullable=True),
        sa.Column("has_card_on_file", sa.Boolean(), nullable=True),
        sa.Column("sos_pay_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_payment_headers_date"),
        "payment_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "payment_custom_fields",
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["sos.payment_headers.id"],
        ),
        sa.PrimaryKeyConstraint("payment_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "payment_header_linked_transactions",
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["sos.payment_headers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "payment_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "payment_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["sos.payment_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_payment_lines_payment_id"),
        "payment_lines",
        ["payment_id"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "payment_line_linked_transactions",
        sa.Column("payment_line_id", sa.Integer(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_line_id"],
            ["sos.payment_lines.id"],
        ),
        sa.PrimaryKeyConstraint(
            "payment_line_id",
            "linked_transaction_id",
            "type",
            "line_number",
        ),
        schema="sos",
    )
    op.create_table(
        "adjustment_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starred", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("number", sa.String(length=128), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("account_name", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("summary_only", sa.Boolean(), nullable=True),
        sa.Column("has_signature", sa.Boolean(), nullable=True),
        sa.Column("force_save", sa.Boolean(), nullable=True),
        sa.Column("keys_raw", sa.JSON(), nullable=True),
        sa.Column("values_raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_adjustment_headers_date"),
        "adjustment_headers",
        ["date"],
        unique=False,
        schema="sos",
    )
    op.create_table(
        "adjustment_custom_fields",
        sa.Column("adjustment_id", sa.Integer(), nullable=False),
        sa.Column("custom_field_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["sos.adjustment_headers.id"],
        ),
        sa.PrimaryKeyConstraint("adjustment_id", "custom_field_id"),
        schema="sos",
    )
    op.create_table(
        "adjustment_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adjustment_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.Text(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("class_name", sa.Text(), nullable=True),
        sa.Column("job_raw", sa.JSON(), nullable=True),
        sa.Column("workcenter_raw", sa.JSON(), nullable=True),
        sa.Column("lot", sa.Text(), nullable=True),
        sa.Column("bin", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity_diff", sa.Float(), nullable=True),
        sa.Column("new_quantity", sa.Float(), nullable=True),
        sa.Column("value_diff", sa.Float(), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("uom_name", sa.String(length=64), nullable=True),
        sa.Column("serials_raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["sos.adjustment_headers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sos",
    )
    op.create_index(
        op.f("ix_sos_adjustment_lines_adjustment_id"),
        "adjustment_lines",
        ["adjustment_id"],
        unique=False,
        schema="sos",
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_sos_adjustment_lines_adjustment_id"),
        table_name="adjustment_lines",
        schema="sos",
    )
    op.drop_table("adjustment_lines", schema="sos")
    op.drop_table("adjustment_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_adjustment_headers_date"),
        table_name="adjustment_headers",
        schema="sos",
    )
    op.drop_table("adjustment_headers", schema="sos")
    op.drop_table("payment_line_linked_transactions", schema="sos")
    op.drop_index(
        op.f("ix_sos_payment_lines_payment_id"),
        table_name="payment_lines",
        schema="sos",
    )
    op.drop_table("payment_lines", schema="sos")
    op.drop_table("payment_header_linked_transactions", schema="sos")
    op.drop_table("payment_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_payment_headers_date"),
        table_name="payment_headers",
        schema="sos",
    )
    op.drop_table("payment_headers", schema="sos")
    op.drop_table("customer_alt_addresses", schema="sos")
    op.drop_table("customer_custom_fields", schema="sos")
    op.drop_table("customers", schema="sos")
    op.drop_table("estimate_line_linked_transactions", schema="sos")
    op.drop_index(
        op.f("ix_sos_estimate_lines_estimate_id"),
        table_name="estimate_lines",
        schema="sos",
    )
    op.drop_table("estimate_lines", schema="sos")
    op.drop_table("estimate_header_linked_transactions", schema="sos")
    op.drop_table("estimate_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_estimate_headers_date"),
        table_name="estimate_headers",
        schema="sos",
    )
    op.drop_table("estimate_headers", schema="sos")
    op.drop_table("sales_receipt_line_linked_transactions", schema="sos")
    op.drop_index(
        op.f("ix_sos_sales_receipt_lines_sales_receipt_id"),
        table_name="sales_receipt_lines",
        schema="sos",
    )
    op.drop_table("sales_receipt_lines", schema="sos")
    op.drop_table("sales_receipt_header_linked_transactions", schema="sos")
    op.drop_table("sales_receipt_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_sales_receipt_headers_date"),
        table_name="sales_receipt_headers",
        schema="sos",
    )
    op.drop_table("sales_receipt_headers", schema="sos")
    op.drop_table("rma_line_linked_transactions", schema="sos")
    op.drop_index(
        op.f("ix_sos_rma_lines_rma_id"),
        table_name="rma_lines",
        schema="sos",
    )
    op.drop_table("rma_lines", schema="sos")
    op.drop_table("rma_header_linked_transactions", schema="sos")
    op.drop_table("rma_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_rma_headers_date"),
        table_name="rma_headers",
        schema="sos",
    )
    op.drop_table("rma_headers", schema="sos")
    op.drop_table("return_line_linked_transactions", schema="sos")
    op.drop_index(
        op.f("ix_sos_return_lines_return_id"),
        table_name="return_lines",
        schema="sos",
    )
    op.drop_table("return_lines", schema="sos")
    op.drop_table("return_header_linked_transactions", schema="sos")
    op.drop_table("return_custom_fields", schema="sos")
    op.drop_index(
        op.f("ix_sos_return_headers_date"),
        table_name="return_headers",
        schema="sos",
    )
    op.drop_table("return_headers", schema="sos")
