"""SOS Sync Table Create

Revision ID: 868c653d8d3b
Revises: 102a6823e36c
Create Date: 2026-09-04 11:05:12.570039
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '868c653d8d3b'
down_revision: str | None = '102a6823e36c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sos_shipment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='ux_sos_shipment_sync_source_key'),
    schema='sos'
    )
    op.create_index(op.f('ix_sos_shipment_sync_sos_shipment_id'), 'shipment_sync', ['sos_shipment_id'], unique=False, schema='sos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_shipment_sync_sos_shipment_id'), table_name='shipment_sync', schema='sos')
    op.drop_table('shipment_sync', schema='sos')
    # ### end Alembic commands ###
