"""Acenda and Data Lake Tables First Create

Revision ID: a7376629a317
Revises: 20260427_0001
Create Date: 2026-07-07 16:27:02.402387
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a7376629a317'
down_revision: str | None = '20260427_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acenda_order_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('purchase_order', sa.String(length=64), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=False),
    sa.Column('sales_channel_id', sa.Integer(), nullable=False),
    sa.Column('sales_channel_name', sa.String(length=64), nullable=False),
    sa.Column('sales_channel_type', sa.String(length=64), nullable=False),
    sa.Column('sales_channel_subtype', sa.String(length=64), nullable=False),
    sa.Column('sales_channel_country', sa.String(length=64), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('create_routings', sa.Boolean(), nullable=False),
    sa.Column('shipping_method', sa.String(length=64), nullable=False),
    sa.Column('shipping_code', sa.String(length=64), nullable=True),
    sa.Column('ship_first_name', sa.String(length=64), nullable=False),
    sa.Column('ship_last_name', sa.String(length=64), nullable=False),
    sa.Column('ship_company', sa.String(length=64), nullable=False),
    sa.Column('ship_address_1', sa.String(length=64), nullable=False),
    sa.Column('ship_address_2', sa.String(length=64), nullable=False),
    sa.Column('ship_city', sa.String(length=64), nullable=False),
    sa.Column('ship_state', sa.String(length=64), nullable=False),
    sa.Column('ship_postal_code', sa.String(length=64), nullable=False),
    sa.Column('ship_country', sa.String(length=64), nullable=False),
    sa.Column('ship_email', sa.String(length=64), nullable=False),
    sa.Column('ship_phone_number', sa.String(length=64), nullable=False),
    sa.Column('bill_first_name', sa.String(length=64), nullable=False),
    sa.Column('bill_last_name', sa.String(length=64), nullable=False),
    sa.Column('bill_company', sa.String(length=64), nullable=False),
    sa.Column('bill_address_1', sa.String(length=64), nullable=False),
    sa.Column('bill_address_2', sa.String(length=64), nullable=False),
    sa.Column('bill_city', sa.String(length=64), nullable=False),
    sa.Column('bill_state', sa.String(length=64), nullable=False),
    sa.Column('bill_postal_code', sa.String(length=64), nullable=False),
    sa.Column('bill_country', sa.String(length=64), nullable=False),
    sa.Column('bill_email', sa.String(length=64), nullable=False),
    sa.Column('bill_phone_number', sa.String(length=64), nullable=False),
    sa.Column('item_tax', sa.Float(), nullable=False),
    sa.Column('ship_tax', sa.Float(), nullable=False),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('total_item_discount', sa.Float(), nullable=False),
    sa.Column('total_shipping_discount', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('requested_ship_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_order_headers_created_at'), 'acenda_order_headers', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_headers_id'), 'acenda_order_headers', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_order_headers_order_number'), 'acenda_order_headers', ['order_number'], unique=False)
    op.create_index(op.f('ix_acenda_order_headers_ordered_at'), 'acenda_order_headers', ['ordered_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_headers_status'), 'acenda_order_headers', ['status'], unique=False)
    op.create_index(op.f('ix_acenda_order_headers_updated_at'), 'acenda_order_headers', ['updated_at'], unique=False)
    op.create_table('acenda_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('line_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('external_sku', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('upc', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('gift_message_price', sa.Float(), nullable=False),
    sa.Column('gift_message_tax_price', sa.Float(), nullable=False),
    sa.Column('total_customization_price', sa.Float(), nullable=False),
    sa.Column('total_customization_tax_price', sa.Float(), nullable=False),
    sa.Column('total_shipping_price', sa.Float(), nullable=False),
    sa.Column('total_shipping_tax_price', sa.Float(), nullable=False),
    sa.Column('total_handling_price', sa.Float(), nullable=False),
    sa.Column('total_item_tax', sa.Float(), nullable=False),
    sa.Column('total_tax_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('other_fees', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('total_item_discount', sa.Float(), nullable=False),
    sa.Column('total_shipping_discount', sa.Float(), nullable=False),
    sa.Column('total_gift_option_price', sa.Float(), nullable=False),
    sa.Column('total_gift_option_tax_price', sa.Float(), nullable=False),
    sa.Column('expected_shipping_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_method', sa.String(length=64), nullable=True),
    sa.Column('external_warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('two_day_shipping', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('quantity_cancelled', sa.Integer(), nullable=False),
    sa.Column('quantity_routed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['acenda_order_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_order_items_created_at'), 'acenda_order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_items_id'), 'acenda_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_order_items_order_id'), 'acenda_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_acenda_order_items_updated_at'), 'acenda_order_items', ['updated_at'], unique=False)
    op.create_table('acenda_ship_advice_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('order_routing_status', sa.String(length=64), nullable=False),
    sa.Column('fulfillment_provider_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('delivery_info_first_name', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_last_name', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_company', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_address_1', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_address_2', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_city', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_state', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_postal_code', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_country', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_email', sa.String(length=64), nullable=False),
    sa.Column('delivery_info_phone_number', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['acenda_order_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_ship_advice_headers_created_at'), 'acenda_ship_advice_headers', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_ship_advice_headers_id'), 'acenda_ship_advice_headers', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_ship_advice_headers_order_id'), 'acenda_ship_advice_headers', ['order_id'], unique=False)
    op.create_index(op.f('ix_acenda_ship_advice_headers_updated_at'), 'acenda_ship_advice_headers', ['updated_at'], unique=False)
    op.create_table('acenda_order_line_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('promotion_code', sa.String(length=64), nullable=False),
    sa.Column('promotion_text', sa.String(length=64), nullable=False),
    sa.Column('affects', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['acenda_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_order_line_discounts_created_at'), 'acenda_order_line_discounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_discounts_id'), 'acenda_order_line_discounts', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_discounts_order_item_id'), 'acenda_order_line_discounts', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_discounts_updated_at'), 'acenda_order_line_discounts', ['updated_at'], unique=False)
    op.create_table('acenda_order_line_kit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['acenda_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_order_line_kit_items_created_at'), 'acenda_order_line_kit_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_kit_items_id'), 'acenda_order_line_kit_items', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_kit_items_order_item_id'), 'acenda_order_line_kit_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_acenda_order_line_kit_items_updated_at'), 'acenda_order_line_kit_items', ['updated_at'], unique=False)
    op.create_table('acenda_order_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rma', sa.String(length=64), nullable=False),
    sa.Column('license_plate_number', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('restock_inventory', sa.Boolean(), nullable=False),
    sa.Column('return_required', sa.Boolean(), nullable=False),
    sa.Column('advance_refund', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('return_tracking', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['acenda_order_headers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['acenda_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_order_returns_created_at'), 'acenda_order_returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_acenda_order_returns_id'), 'acenda_order_returns', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_order_returns_order_id'), 'acenda_order_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_acenda_order_returns_order_item_id'), 'acenda_order_returns', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_acenda_order_returns_updated_at'), 'acenda_order_returns', ['updated_at'], unique=False)
    op.create_table('acenda_ship_advice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('ship_advice_id', sa.Integer(), nullable=False),
    sa.Column('inventory_detail_id', sa.Integer(), nullable=False),
    sa.Column('quantity_rerouted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['acenda_order_items.id'], ),
    sa.ForeignKeyConstraint(['ship_advice_id'], ['acenda_ship_advice_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acenda_ship_advice_items_id'), 'acenda_ship_advice_items', ['id'], unique=False)
    op.create_index(op.f('ix_acenda_ship_advice_items_order_item_id'), 'acenda_ship_advice_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_acenda_ship_advice_items_ship_advice_id'), 'acenda_ship_advice_items', ['ship_advice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acenda_ship_advice_items_ship_advice_id'), table_name='acenda_ship_advice_items')
    op.drop_index(op.f('ix_acenda_ship_advice_items_order_item_id'), table_name='acenda_ship_advice_items')
    op.drop_index(op.f('ix_acenda_ship_advice_items_id'), table_name='acenda_ship_advice_items')
    op.drop_table('acenda_ship_advice_items')
    op.drop_index(op.f('ix_acenda_order_returns_updated_at'), table_name='acenda_order_returns')
    op.drop_index(op.f('ix_acenda_order_returns_order_item_id'), table_name='acenda_order_returns')
    op.drop_index(op.f('ix_acenda_order_returns_order_id'), table_name='acenda_order_returns')
    op.drop_index(op.f('ix_acenda_order_returns_id'), table_name='acenda_order_returns')
    op.drop_index(op.f('ix_acenda_order_returns_created_at'), table_name='acenda_order_returns')
    op.drop_table('acenda_order_returns')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_updated_at'), table_name='acenda_order_line_kit_items')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_order_item_id'), table_name='acenda_order_line_kit_items')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_id'), table_name='acenda_order_line_kit_items')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_created_at'), table_name='acenda_order_line_kit_items')
    op.drop_table('acenda_order_line_kit_items')
    op.drop_index(op.f('ix_acenda_order_line_discounts_updated_at'), table_name='acenda_order_line_discounts')
    op.drop_index(op.f('ix_acenda_order_line_discounts_order_item_id'), table_name='acenda_order_line_discounts')
    op.drop_index(op.f('ix_acenda_order_line_discounts_id'), table_name='acenda_order_line_discounts')
    op.drop_index(op.f('ix_acenda_order_line_discounts_created_at'), table_name='acenda_order_line_discounts')
    op.drop_table('acenda_order_line_discounts')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_updated_at'), table_name='acenda_ship_advice_headers')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_order_id'), table_name='acenda_ship_advice_headers')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_id'), table_name='acenda_ship_advice_headers')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_created_at'), table_name='acenda_ship_advice_headers')
    op.drop_table('acenda_ship_advice_headers')
    op.drop_index(op.f('ix_acenda_order_items_updated_at'), table_name='acenda_order_items')
    op.drop_index(op.f('ix_acenda_order_items_order_id'), table_name='acenda_order_items')
    op.drop_index(op.f('ix_acenda_order_items_id'), table_name='acenda_order_items')
    op.drop_index(op.f('ix_acenda_order_items_created_at'), table_name='acenda_order_items')
    op.drop_table('acenda_order_items')
    op.drop_index(op.f('ix_acenda_order_headers_updated_at'), table_name='acenda_order_headers')
    op.drop_index(op.f('ix_acenda_order_headers_status'), table_name='acenda_order_headers')
    op.drop_index(op.f('ix_acenda_order_headers_ordered_at'), table_name='acenda_order_headers')
    op.drop_index(op.f('ix_acenda_order_headers_order_number'), table_name='acenda_order_headers')
    op.drop_index(op.f('ix_acenda_order_headers_id'), table_name='acenda_order_headers')
    op.drop_index(op.f('ix_acenda_order_headers_created_at'), table_name='acenda_order_headers')
    op.drop_table('acenda_order_headers')
    # ### end Alembic commands ###
