"""create ksp shipment tables

Revision ID: abf181ebf509
Revises: 683a1677fd58
Create Date: 2026-09-02 22:16:07.280723
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "abf181ebf509"
down_revision: str | None = "683a1677fd58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS warehouse_data")
    op.create_table(
        "ksp_ship_headers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cust_ref", sa.String(), nullable=False),
        sa.Column("cust_po_no", sa.String(), nullable=False),
        sa.Column("delivered_to_wms_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cust_ref", "cust_po_no", name="uq_ksp_ship_headers_cust_ref_po"
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_po_no"),
        "ksp_ship_headers",
        ["cust_po_no"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_delivered_to_wms_date"),
        "ksp_ship_headers",
        ["delivered_to_wms_date"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_headers_order_status"),
        "ksp_ship_headers",
        ["order_status"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "ksp_ship_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ship_header_id", sa.Integer(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("tracking_no", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("package_weight_lbs", sa.Float(), nullable=False),
        sa.Column("dim_weight_lbs", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ship_header_id"],
            ["warehouse_data.ksp_ship_headers.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_no", name="uq_ksp_ship_details_tracking_no"),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_carrier"),
        "ksp_ship_details",
        ["carrier"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_details_date"),
        "ksp_ship_details",
        ["date"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        "ix_warehouse_data_ksp_ship_details_shipment_header_id",
        "ksp_ship_details",
        ["ship_header_id"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_table(
        "ksp_ship_detail_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ship_detail_id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ship_detail_id"],
            ["warehouse_data.ksp_ship_details.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ship_detail_id", "item", name="uq_ksp_ship_detail_items_detail_item"
        ),
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_item"),
        "ksp_ship_detail_items",
        ["item"],
        unique=False,
        schema="warehouse_data",
    )
    op.create_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_ship_detail_id"),
        "ksp_ship_detail_items",
        ["ship_detail_id"],
        unique=False,
        schema="warehouse_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_ship_detail_id"),
        table_name="ksp_ship_detail_items",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_detail_items_item"),
        table_name="ksp_ship_detail_items",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_detail_items", schema="warehouse_data")
    op.drop_index(
        "ix_warehouse_data_ksp_ship_details_shipment_header_id",
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_date"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_details_carrier"),
        table_name="ksp_ship_details",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_details", schema="warehouse_data")
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_order_status"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_delivered_to_wms_date"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_index(
        op.f("ix_warehouse_data_ksp_ship_headers_cust_po_no"),
        table_name="ksp_ship_headers",
        schema="warehouse_data",
    )
    op.drop_table("ksp_ship_headers", schema="warehouse_data")
    # ### end Alembic commands ###
