"""Acenda to SOS Tables

Revision ID: b2f95d2def23
Revises: 3c9d1e5f7a6b
Create Date: 2026-07-22 12:42:29.214227
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2f95d2def23'
down_revision: str | None = '3c9d1e5f7a6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_header_key', sa.String(length=255), nullable=False),
    sa.Column('source_line_key', sa.String(length=512), nullable=False),
    sa.Column('payload_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sos_order_id', sa.Integer(), nullable=True),
    sa.Column('sos_line_id', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_line_key', name='ux_sos_order_sync_source_line'),
    schema='sos'
    )
    op.create_index(op.f('ix_sos_sales_order_sync_sos_order_id'), 'sales_order_sync', ['sos_order_id'], unique=False, schema='sos')
    op.alter_column('order_headers', 'fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='acenda')
    op.alter_column('order_headers', 'sales_channel_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='acenda')
    op.drop_index(op.f('ix_order_headers_created_at'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_order_headers_id'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_order_headers_order_number'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_order_headers_ordered_at'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_order_headers_status'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_order_headers_updated_at'), table_name='order_headers', schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_created_at'), 'order_headers', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_id'), 'order_headers', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_order_number'), 'order_headers', ['order_number'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_ordered_at'), 'order_headers', ['ordered_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_status'), 'order_headers', ['status'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_headers_updated_at'), 'order_headers', ['updated_at'], unique=False, schema='acenda')
    op.alter_column('order_items', 'sku',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               schema='acenda')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_order_items_updated_at'), table_name='order_items', schema='acenda')
    op.create_index(op.f('ix_acenda_order_items_created_at'), 'order_items', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_items_id'), 'order_items', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_items_updated_at'), 'order_items', ['updated_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_order_line_discounts_created_at'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_order_line_discounts_id'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_order_line_discounts_order_item_id'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_order_line_discounts_updated_at'), table_name='order_line_discounts', schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_discounts_created_at'), 'order_line_discounts', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_discounts_id'), 'order_line_discounts', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_discounts_order_item_id'), 'order_line_discounts', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_discounts_updated_at'), 'order_line_discounts', ['updated_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_order_line_kit_items_created_at'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_order_line_kit_items_id'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_order_line_kit_items_order_item_id'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_order_line_kit_items_updated_at'), table_name='order_line_kit_items', schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_kit_items_created_at'), 'order_line_kit_items', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_kit_items_id'), 'order_line_kit_items', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_kit_items_order_item_id'), 'order_line_kit_items', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_line_kit_items_updated_at'), 'order_line_kit_items', ['updated_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_order_returns_created_at'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_order_returns_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_order_returns_order_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_order_returns_order_item_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_order_returns_updated_at'), table_name='order_returns', schema='acenda')
    op.create_index(op.f('ix_acenda_order_returns_created_at'), 'order_returns', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_returns_id'), 'order_returns', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_returns_order_id'), 'order_returns', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_returns_order_item_id'), 'order_returns', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_order_returns_updated_at'), 'order_returns', ['updated_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_ship_advice_headers_created_at'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_ship_advice_headers_id'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_ship_advice_headers_order_id'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_ship_advice_headers_updated_at'), table_name='ship_advice_headers', schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_headers_created_at'), 'ship_advice_headers', ['created_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_headers_id'), 'ship_advice_headers', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_headers_order_id'), 'ship_advice_headers', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_headers_updated_at'), 'ship_advice_headers', ['updated_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_ship_advice_items_id'), table_name='ship_advice_items', schema='acenda')
    op.drop_index(op.f('ix_ship_advice_items_order_item_id'), table_name='ship_advice_items', schema='acenda')
    op.drop_index(op.f('ix_ship_advice_items_ship_advice_id'), table_name='ship_advice_items', schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_items_id'), 'ship_advice_items', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_items_order_item_id'), 'ship_advice_items', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_acenda_ship_advice_items_ship_advice_id'), 'ship_advice_items', ['ship_advice_id'], unique=False, schema='acenda')
    op.alter_column('invoice_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
               schema='sos')
    op.drop_index(op.f('ix_invoice_headers_date'), table_name='invoice_headers', schema='sos')
    op.create_index(op.f('ix_sos_invoice_headers_date'), 'invoice_headers', ['date'], unique=False, schema='sos')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines', schema='sos')
    op.create_index(op.f('ix_sos_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='sos')
    op.alter_column('item_receipt_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
               schema='sos')
    op.drop_index(op.f('ix_item_receipt_headers_date'), table_name='item_receipt_headers', schema='sos')
    op.create_index(op.f('ix_sos_item_receipt_headers_date'), 'item_receipt_headers', ['date'], unique=False, schema='sos')
    op.drop_index(op.f('ix_item_receipt_lines_item_receipt_id'), table_name='item_receipt_lines', schema='sos')
    op.create_index(op.f('ix_sos_item_receipt_lines_item_receipt_id'), 'item_receipt_lines', ['item_receipt_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_item_receipt_other_costs_item_receipt_id'), table_name='item_receipt_other_costs', schema='sos')
    op.create_index(op.f('ix_sos_item_receipt_other_costs_item_receipt_id'), 'item_receipt_other_costs', ['item_receipt_id'], unique=False, schema='sos')
    op.alter_column('items', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
               schema='sos')
    op.alter_column('sales_order_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
               schema='sos')
    op.drop_index(op.f('ix_sales_order_headers_date'), table_name='sales_order_headers', schema='sos')
    op.create_index(op.f('ix_sos_sales_order_headers_date'), 'sales_order_headers', ['date'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sales_order_lines_sales_order_id'), table_name='sales_order_lines', schema='sos')
    op.create_index(op.f('ix_sos_sales_order_lines_sales_order_id'), 'sales_order_lines', ['sales_order_id'], unique=False, schema='sos')
    op.alter_column('shipment_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=sa.text('0'),
               schema='sos')
    op.drop_index(op.f('ix_shipment_headers_date'), table_name='shipment_headers', schema='sos')
    op.create_index(op.f('ix_sos_shipment_headers_date'), 'shipment_headers', ['date'], unique=False, schema='sos')
    op.drop_index(op.f('ix_shipment_lines_shipment_id'), table_name='shipment_lines', schema='sos')
    op.create_index(op.f('ix_sos_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False, schema='sos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_shipment_lines_shipment_id'), table_name='shipment_lines', schema='sos')
    op.create_index(op.f('ix_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sos_shipment_headers_date'), table_name='shipment_headers', schema='sos')
    op.create_index(op.f('ix_shipment_headers_date'), 'shipment_headers', ['date'], unique=False, schema='sos')
    op.alter_column('shipment_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None,
               schema='sos')
    op.drop_index(op.f('ix_sos_sales_order_lines_sales_order_id'), table_name='sales_order_lines', schema='sos')
    op.create_index(op.f('ix_sales_order_lines_sales_order_id'), 'sales_order_lines', ['sales_order_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sos_sales_order_headers_date'), table_name='sales_order_headers', schema='sos')
    op.create_index(op.f('ix_sales_order_headers_date'), 'sales_order_headers', ['date'], unique=False, schema='sos')
    op.alter_column('sales_order_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None,
               schema='sos')
    op.alter_column('items', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None,
               schema='sos')
    op.drop_index(op.f('ix_sos_item_receipt_other_costs_item_receipt_id'), table_name='item_receipt_other_costs', schema='sos')
    op.create_index(op.f('ix_item_receipt_other_costs_item_receipt_id'), 'item_receipt_other_costs', ['item_receipt_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sos_item_receipt_lines_item_receipt_id'), table_name='item_receipt_lines', schema='sos')
    op.create_index(op.f('ix_item_receipt_lines_item_receipt_id'), 'item_receipt_lines', ['item_receipt_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sos_item_receipt_headers_date'), table_name='item_receipt_headers', schema='sos')
    op.create_index(op.f('ix_item_receipt_headers_date'), 'item_receipt_headers', ['date'], unique=False, schema='sos')
    op.alter_column('item_receipt_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None,
               schema='sos')
    op.drop_index(op.f('ix_sos_invoice_lines_invoice_id'), table_name='invoice_lines', schema='sos')
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='sos')
    op.drop_index(op.f('ix_sos_invoice_headers_date'), table_name='invoice_headers', schema='sos')
    op.create_index(op.f('ix_invoice_headers_date'), 'invoice_headers', ['date'], unique=False, schema='sos')
    op.alter_column('invoice_headers', 'sync_token',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None,
               schema='sos')
    op.drop_index(op.f('ix_acenda_ship_advice_items_ship_advice_id'), table_name='ship_advice_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_items_order_item_id'), table_name='ship_advice_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_items_id'), table_name='ship_advice_items', schema='acenda')
    op.create_index(op.f('ix_ship_advice_items_ship_advice_id'), 'ship_advice_items', ['ship_advice_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_ship_advice_items_order_item_id'), 'ship_advice_items', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_ship_advice_items_id'), 'ship_advice_items', ['id'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_updated_at'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_order_id'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_id'), table_name='ship_advice_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_ship_advice_headers_created_at'), table_name='ship_advice_headers', schema='acenda')
    op.create_index(op.f('ix_ship_advice_headers_updated_at'), 'ship_advice_headers', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_ship_advice_headers_order_id'), 'ship_advice_headers', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_ship_advice_headers_id'), 'ship_advice_headers', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_ship_advice_headers_created_at'), 'ship_advice_headers', ['created_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_acenda_order_returns_updated_at'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_returns_order_item_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_returns_order_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_returns_id'), table_name='order_returns', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_returns_created_at'), table_name='order_returns', schema='acenda')
    op.create_index(op.f('ix_order_returns_updated_at'), 'order_returns', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_returns_order_item_id'), 'order_returns', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_returns_order_id'), 'order_returns', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_returns_id'), 'order_returns', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_returns_created_at'), 'order_returns', ['created_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_updated_at'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_order_item_id'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_id'), table_name='order_line_kit_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_kit_items_created_at'), table_name='order_line_kit_items', schema='acenda')
    op.create_index(op.f('ix_order_line_kit_items_updated_at'), 'order_line_kit_items', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_kit_items_order_item_id'), 'order_line_kit_items', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_kit_items_id'), 'order_line_kit_items', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_kit_items_created_at'), 'order_line_kit_items', ['created_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_discounts_updated_at'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_discounts_order_item_id'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_discounts_id'), table_name='order_line_discounts', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_line_discounts_created_at'), table_name='order_line_discounts', schema='acenda')
    op.create_index(op.f('ix_order_line_discounts_updated_at'), 'order_line_discounts', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_discounts_order_item_id'), 'order_line_discounts', ['order_item_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_discounts_id'), 'order_line_discounts', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_line_discounts_created_at'), 'order_line_discounts', ['created_at'], unique=False, schema='acenda')
    op.drop_index(op.f('ix_acenda_order_items_updated_at'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_items_order_id'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_items_id'), table_name='order_items', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_items_created_at'), table_name='order_items', schema='acenda')
    op.create_index(op.f('ix_order_items_updated_at'), 'order_items', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False, schema='acenda')
    op.alter_column('order_items', 'sku',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_updated_at'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_status'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_ordered_at'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_order_number'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_id'), table_name='order_headers', schema='acenda')
    op.drop_index(op.f('ix_acenda_order_headers_created_at'), table_name='order_headers', schema='acenda')
    op.create_index(op.f('ix_order_headers_updated_at'), 'order_headers', ['updated_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_headers_status'), 'order_headers', ['status'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_headers_ordered_at'), 'order_headers', ['ordered_at'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_headers_order_number'), 'order_headers', ['order_number'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_headers_id'), 'order_headers', ['id'], unique=False, schema='acenda')
    op.create_index(op.f('ix_order_headers_created_at'), 'order_headers', ['created_at'], unique=False, schema='acenda')
    op.alter_column('order_headers', 'sales_channel_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='acenda')
    op.execute(
        "UPDATE acenda.order_headers "
        "SET fields = '{}'::json "
        "WHERE fields IS NULL"
    )
    op.alter_column('order_headers', 'fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='acenda')
    op.drop_index(op.f('ix_sos_sales_order_sync_sos_order_id'), table_name='sales_order_sync', schema='sos')
    op.drop_table('sales_order_sync', schema='sos')
    # ### end Alembic commands ###
