"""Data Lake Table Create

Revision ID: c8d8c436f3fc
Revises: a7376629a317
Create Date: 2026-07-07 16:43:33.090805
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c8d8c436f3fc'
down_revision: str | None = 'a7376629a317'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_lake_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('landed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('loaded_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('source_min_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_max_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_data_lake_files_claimed_at'), 'data_lake_files', ['claimed_at'], unique=False)
    op.create_index(op.f('ix_data_lake_files_entity_name'), 'data_lake_files', ['entity_name'], unique=False)
    op.create_index(op.f('ix_data_lake_files_landed_at'), 'data_lake_files', ['landed_at'], unique=False)
    op.create_index(op.f('ix_data_lake_files_source_name'), 'data_lake_files', ['source_name'], unique=False)
    op.create_index(op.f('ix_data_lake_files_status'), 'data_lake_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_lake_files_status'), table_name='data_lake_files')
    op.drop_index(op.f('ix_data_lake_files_source_name'), table_name='data_lake_files')
    op.drop_index(op.f('ix_data_lake_files_landed_at'), table_name='data_lake_files')
    op.drop_index(op.f('ix_data_lake_files_entity_name'), table_name='data_lake_files')
    op.drop_index(op.f('ix_data_lake_files_claimed_at'), table_name='data_lake_files')
    op.drop_table('data_lake_files')
    # ### end Alembic commands ###
