services:
  api:
    container_name: bokser_app_api_staging
    ports:
      - ${STAGING_API_HOST_PORT:-8011}:8000
    environment:
      APP_ENV: staging

  worker:
    container_name: bokser_app_worker_staging
    environment:
      APP_ENV: staging
    volumes:
      - ../src:/app/src:ro
      - ${LAKE_HOST_PATH_STAGING:-/volume1/data_lake/staging}:${LAKE_ROOT:-/data_lake}
