services:
  migrate:
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:5514
        syslog-format: rfc3164
        tag: "{{.Name}}"

  bokser_app_api:
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:5514
        syslog-format: rfc3164
        tag: "{{.Name}}"

  bokser_app_worker:
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:5514
        syslog-format: rfc3164
        tag: "{{.Name}}"
